"use client";

import React from "react";
import MdiIcon from "@/components/MdiIcon";

export default function PlanExportPDF({
  plannerState = {},
  planningResults = null,
  channels = [],
  onTriggerPrint = () => {
    if (typeof window !== "undefined") window.print();
  },
}) {
  const totalBudget = plannerState?.totalBudget || 500000;
  const flightDuration = plannerState?.flightDuration || "1 Month";
  const objective = plannerState?.campaignObjective || "Brand Awareness";
  const targetCities = plannerState?.targetCities?.join(", ") || "National Grid";
  const sector = plannerState?.industrySector || "Fintech";

  return (
    <div className="w-full bg-[#0B1E3B] text-white p-6 md:p-8 rounded-[10px] border border-white/10 space-y-6 font-sans">
      <div className="flex items-center justify-between border-b border-white/10 pb-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono font-bold uppercase text-[#FF5A1F] mb-1">
            <MdiIcon name="file-pdf-box" className="text-sm" /> OTZ Media Planning Report
          </div>
          <h2 className="text-2xl font-black font-display text-white">
            Campaign Plan PDF Summary
          </h2>
          <p className="text-xs text-slate-300">
            Official media allocation proposal generated by OTZ AI Engine.
          </p>
        </div>

        <button
          type="button"
          onClick={onTriggerPrint}
          className="inline-flex items-center gap-2 rounded-[6px] bg-[#FF5A1F] text-[#0B1E3B] font-bold px-4 py-2 text-xs uppercase tracking-wider hover:opacity-90 transition-all cursor-pointer"
        >
          <MdiIcon name="printer" className="text-sm" /> Print / Save PDF
        </button>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs font-sans bg-[#132A4F] p-4 rounded-[8px] border border-white/10">
        <div>
          <span className="font-mono text-[9px] uppercase tracking-wider text-slate-400 block">Total Budget</span>
          <span className="font-mono font-bold text-[#FF5A1F] text-base">₹{Number(totalBudget).toLocaleString("en-IN")}</span>
        </div>
        <div>
          <span className="font-mono text-[9px] uppercase tracking-wider text-slate-400 block">Flight Duration</span>
          <span className="font-bold text-white text-base">{flightDuration}</span>
        </div>
        <div>
          <span className="font-mono text-[9px] uppercase tracking-wider text-slate-400 block">Objective</span>
          <span className="font-bold text-white text-base">{objective}</span>
        </div>
        <div>
          <span className="font-mono text-[9px] uppercase tracking-wider text-slate-400 block">Markets</span>
          <span className="font-bold text-white text-base">{targetCities}</span>
        </div>
      </div>

      {channels.length > 0 && (
        <div className="space-y-3">
          <h4 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-300">Channel Share Breakdown</h4>
          <div className="divide-y divide-white/10 border border-white/10 rounded-[8px] bg-[#132A4F] overflow-hidden text-xs">
            {channels.map((ch) => (
              <div key={ch.id} className="p-3 flex items-center justify-between">
                <span className="font-bold text-white flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: ch.color }}></span>
                  {ch.name}
                </span>
                <div className="flex items-center gap-4 font-mono">
                  <span className="text-[#FF5A1F] font-bold">{ch.share}%</span>
                  <span className="text-slate-300">₹{Math.round((ch.share / 100) * totalBudget).toLocaleString("en-IN")}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
